projects:
  app:
    schemaPath: './packages/api/src/schema.graphql'
    includes: ['**/*.graphql']
    extensions:
      endpoints:
        default: 'http://localhost:4000'
  prisma:
    schemaPath: './packages/api/prisma/generated/prisma.graphql'
    extensions:
      prisma: prisma/prisma.yml
